# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d2becc2c-cd7b-46c7-894c-c1305eb3d0bf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d2becc2c-cd7b-46c7-894c-c1305eb3d0bf".device = "/dev/disk/by-uuid/d2becc2c-cd7b-46c7-894c-c1305eb3d0bf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA67-6699";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-05269bae-490f-4b00-9acf-ee7e5de0eb8d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
